Restructuring some of the debug commands

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -45,17 +45,17 @@ jobs:
       - name: Verify FFmpeg and FFprobe Binaries
         shell: bash
         run: |
-          if [ -f "ffmpeg_dir" ]; then
+          if [ -f "ffmpeg_dir/ffmpeg" ]; then
             echo "ffmpeg is present."
-            chmod +x ffmpeg_dir
+            chmod +x ffmpeg_dir/ffmpeg
           else
             echo "ffmpeg is missing." >&2
             exit 1
           fi
       
-          if [ -f "ffmpeg_dir" ]; then
+          if [ -f "ffmpeg_dir/ffprobe" ]; then
             echo "ffprobe is present."
-            chmod +x ffmpeg_dir
+            chmod +x ffmpeg_dir/ffprobe
           else
             echo "ffprobe is missing." >&2
             exit 1
@@ -80,41 +80,45 @@ jobs:
           --log-level=DEBUG \
           --debug=all \
           --osx-bundle-identifier "com.github.themightyzq.ZQSFXAudioSplitter"
+
+      - name: List Contents of App Bundle
+        shell: bash
+        run: |
+                echo "Listing contents of the app bundle:"
+                find "dist/ZQ SFX Audio Splitter.app"  
       
       - name: Set Execute Permissions on macOS Executable and FFmpeg/FFprobe
         shell: bash
         run: |
-            APP_PATH="dist/ZQ SFX Audio Splitter.app/Contents/MacOS/ZQ SFX Audio Splitter"
-            FFMPEG_PATH="dist/ZQ SFX Audio Splitter.app/Contents/Resources/ffmpeg"
-            FFPROBE_PATH="dist/ZQ SFX Audio Splitter.app/Contents/Resources/ffprobe"
-            if [ -f "$APP_PATH" ]; then
-              chmod +x "$APP_PATH"
-              echo "Set execute permissions on $APP_PATH"
-            else
-              echo "Executable not found at $APP_PATH" >&2
-              exit 1
-            fi
-            if [ -f "$FFMPEG_PATH" ]; then
-              chmod +x "$FFMPEG_PATH"
-              echo "Set execute permissions on $FFMPEG_PATH"
-            else
-              echo "FFmpeg not found at $FFMPEG_PATH" >&2
-              exit 1
-            fi
-            if [ -f "$FFPROBE_PATH" ]; then
-              chmod +x "$FFPROBE_PATH"
-              echo "Set execute permissions on $FFPROBE_PATH"
-            else
-              echo "FFprobe not found at $FFPROBE_PATH" >&2
-              exit 1
-            fi
-            
-      - name: List Contents of App Bundle
-        shell: bash
-        run: |
-              echo "Listing contents of the app bundle:"
-              find "dist/ZQ SFX Audio Splitter.app"    
-
+          set -x  # Enable script debugging
+          APP_PATH="dist/ZQ SFX Audio Splitter.app/Contents/MacOS/ZQ SFX Audio Splitter"
+          FFMPEG_PATH="dist/ZQ SFX Audio Splitter.app/Contents/Resources/ffmpeg"
+          FFPROBE_PATH="dist/ZQ SFX Audio Splitter.app/Contents/Resources/ffprobe"
+          if [ -f "$APP_PATH" ]; then
+            chmod +x "$APP_PATH"
+            echo "Set execute permissions on $APP_PATH"
+          else
+            echo "Executable not found at $APP_PATH" >&2
+            ls -la "dist/ZQ SFX Audio Splitter.app/Contents/MacOS"
+            exit 1
+          fi
+          if [ -f "$FFMPEG_PATH" ]; then
+            chmod +x "$FFMPEG_PATH"
+            echo "Set execute permissions on $FFMPEG_PATH"
+          else
+            echo "FFmpeg not found at $FFMPEG_PATH" >&2
+            ls -la "dist/ZQ SFX Audio Splitter.app/Contents/Resources"
+            exit 1
+          fi
+          if [ -f "$FFPROBE_PATH" ]; then
+            chmod +x "$FFPROBE_PATH"
+            echo "Set execute permissions on $FFPROBE_PATH"
+          else
+            echo "FFprobe not found at $FFPROBE_PATH" >&2
+            ls -la "dist/ZQ SFX Audio Splitter.app/Contents/Resources"
+            exit 1
+          fi
+    
       - name: Upload macOS Artifact
         uses: actions/upload-artifact@v3
         with:
